#! /usr/bin/bash

export DISPLAY=:0
export XAUTHORITY=/home/osipov/.Xauthority

status="$(cat /sys/class/drm/card0-HDMI-A-1/status)"

if [ "${status}" == disconnected ]; then
    /usr/bin/xrandr --output DVI-I-1 --auto --output HDMI-1 --off 2> /home/osipov/.udev/hdmi-hotplug.log
elif [ "${status}" == connected ]; then
    /usr/bin/xrandr --output DVI-I-1 --auto --output HDMI-1 --auto --right-of DVI-I-1 2> /home/osipov/.udev/hdmi-hotplug.log
else /usr/bin/xrandr --auto
fi
